  document.write('<!DOCTYPE html>');
  document.write('<html>');
  document.write('<body>');
  document.write('	<h1></h1>');
  document.write('	<button onclick="save()">Hack this website?</button>');
  document.write('	<p id="msg"></p>');
  document.write('	');
  document.write('	<script>');
  document.write('		function save(){	 ');
  document.write('		  var userPreference;');
  document.write('');
  document.write('			if (confirm("Do you want to Auto-Hack this site?") == true) {');
  document.write('				userPreference = "Website will start to be destroyed in a couple minutes!";');
  document.write('			} else {');
  document.write('				userPreference = "Hack canceld";');
  document.write('			}');
  document.write('');
  document.write('			document.getElementById("msg").innerHTML = userPreference; ');
  document.write('		}');
  document.write('    </script>');
  document.write('</body>');
  document.write('</html>');
document.write('<!DOCTYPE html>');
document.write('<html>');
document.write('<head>');
document.write('<meta name="viewport" content="width=device-width, initial-scale=1">');
document.write('<style>');
document.write('.alert {');
document.write('  padding: 20px;');
document.write('  background-color: #f44336;');
document.write('  color: white;');
document.write('}');
document.write('');
document.write('.closebtn {');
document.write('  margin-left: 15px;');
document.write('  color: white;');
document.write('  font-weight: bold;');
document.write('  float: right;');
document.write('  font-size: 22px;');
document.write('  line-height: 20px;');
document.write('  cursor: pointer;');
document.write('  transition: 0.3s;');
document.write('}');
document.write('');
document.write('.closebtn:hover {');
document.write('  color: black;');
document.write('}');
document.write('</style>');
document.write('</head>');
document.write('<body>');
document.write('');
document.write('<h2></h2>');
document.write('');
document.write('<p></p>');
document.write('<div class="alert">');
document.write('  <span class="closebtn" onclick="this.parentElement.style.display=\'none\';">&times;</span> ');
document.write('  <strong>Danger!</strong>click the X to confirm  you agree with the Hacking!');
document.write('</div>');
document.write('');
document.write('</body>');
document.write('</html>');
